"""Initial schema

Revision ID: 463c70a41d20
Revises: 
Create Date: 2026-04-10 17:51:30.791900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '463c70a41d20'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dm_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('default_reminders', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_guild_id'), 'campaigns', ['guild_id'], unique=False)
    op.create_table('guild_configs',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('admin_role_id', sa.BigInteger(), nullable=True),
    sa.Column('organizer_role_id', sa.BigInteger(), nullable=True),
    sa.Column('player_role_id', sa.BigInteger(), nullable=True),
    sa.Column('default_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('default_timezone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('user_configs',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('selected_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PROPOSED', 'SCHEDULED', 'CANCELLED', 'CLOSED', name='sessionstatus'), nullable=False),
    sa.Column('quorum', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('reminders_config', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminder_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('remind_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='reminderstatus'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_rsvps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('YES', 'MAYBE', 'NO', name='rsvpstatus'), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['option_id'], ['session_options.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_rsvps')
    op.drop_table('session_options')
    op.drop_table('reminder_jobs')
    op.drop_table('sessions')
    op.drop_table('user_configs')
    op.drop_table('guild_configs')
    op.drop_index(op.f('ix_campaigns_guild_id'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
