"""add rsvp priority

Revision ID: e92a348d15b2
Revises: 463c70a41d20
Create Date: 2026-04-10 18:41:55.059758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e92a348d15b2'
down_revision: Union[str, Sequence[str], None] = '463c70a41d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_rsvps', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_rsvps', 'priority')
    # ### end Alembic commands ###
